baseURL = "http://www.johnrizzo.net"
title = "John Rizzo"
theme = "jnet"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 6
enableEmoji = true

# [services]
# [services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"

[markup.highlight]
  noClasses = false

[params]
  author = "John Rizzo"
  description = "John Rizzo"
  keywords = "blog,developer,personal"
  info = [
    "Trusted Leader | CTO | Technologist",
    "Enjoys building complex distributed systems and infrastructure"
  ]
  avatarURL = "images/avatar.jpg"
  gravatar = "johnrizzo1@gmail.com"
  dateFormat = "January 2, 2006"
  since = 2019
  # commit = "https://github.com/luizdepra/hugo-coder/tree/"
  rtl = false
  colorScheme = "auto" # auto dark or light
  hideColorSchemeToggle = false # Hide the toggle button, along with the associated vertical divider
  maxSeeAlsoItems = 5 # Series see also post count
  customCSS = []
  customSCSS = [] # Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
  customJS = []
  customRemoteJS = [] # Custom remote JS files

  primaryColor = "#000000"
  textPrimaryColor = "#292929"

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
[params.googleTagManager]
  id = "G-C9Z8NQ33SG"

# If you want to implement a Content-Security-Policy, add this section
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'", "https://www.youtube.com"]
# imgsrc = ["'self'"]
# objectsrc = ["'none'"]
# stylesrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://fonts.googleapis.com/",
#   "https://cdn.jsdelivr.net/",
# ]
# scriptsrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://www.google-analytics.com",
#   "https://cdn.jsdelivr.net/",
# ]
# prefetchsrc = ["'self'"]
# # connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

  [[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/johnrizzo1/"

  [[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/johnrizzo1/"

  [[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 4
  url = "https://www.linkedin.com/in/johnrizzo1/"

[languages.en]
  languageName = ":us:"

  # [[languages.en.menu.main]]
  # name = "About"
  # weight = 1
  # url = "about/"

  [[languages.en.menu.main]]
  name = "Blog"
  weight = 2
  url = "posts/"

  [[languages.en.menu.main]]
  name = "CV"
  weight = 3
  url = "cv/"

  # [[languages.en.menu.main]]
  # name = "Projects"
  # weight = 3
  # url = "projects/"

  # [[languages.en.menu.main]]
  # name = "Contact me"
  # weight = 5
  # url = "contact/"

[params.profile]
  enable = true
  name = "John Rizzo"
  tagline = "Trusted Leader | CTO | Technologist"
  avatar = "avatar.jpg"

[params.contact]
  enable = true
  location = "New York"

  [[params.contact.list]]
    icon = "fas fa-phone-square"
    url = "tel:#"
    text = "0123 4567 890"

  [[params.contact.list]]
    icon = "fas fa-envelope-square"
    url = "mailto:#"
    text = "simon.doe@yourwebsite.com"

  [[params.contact.list]]
    icon = "fas fa-globe"
    url = "#"
    text = "www.yourwebsite.com"

[params.skills]
  enable = true

  [[params.skills.list]]
  title = "Technical"
  [[params.skills.list.items]]
  details = "JavaScript/Angular/React/Vue"
  [[params.skills.list.items]]
  details = "Python/Ruby/PHP"
  [[params.skills.list.items]]
  details = "Node.js/ASP.NET"
  [[params.skills.list.items]]
  details = "PostgreSQL/MySQL"
  [[params.skills.list.items]]
  details = "Object-oriented design"
  [[params.skills.list.items]]
  details = "Design and implement database structures"
  [[params.skills.list.items]]
  details = "Lead and deliver complex software systems"

  [[params.skills.list]]
  title = "Professional"
  [[params.skills.list.items]]
  details = "Effective communication"
  [[params.skills.list.items]]
  details = "Team player"
  [[params.skills.list.items]]
  details = "Strong problem solver"
  [[params.skills.list.items]]
  details = "Good time management"

[params.education]
  enable = true

  [[params.education.list]]
  degree = "MSc in Computer Science"
  university = "University College London"
  dates = "2010 - 2011"

  [[params.education.list]]
  degree = "BSc Maths and Physics"
  university = "Imperial College London"
  dates = "2007 - 2010"

[params.awards]
  enable = true

  [[params.awards.list]]
  name = "Award Lorem Ipsum"
  body = "Microsoft lorem ipsum"
  date = "2019"

  [[params.awards.list]]
  name = "Award Donec Sodales"
  body = "Oracle Aenean"
  date = "2017"

[params.languages]
  enable = true

  [[params.languages.list]]
  name = "English"
  level = "Native"

  [[params.languages.list]]
  name = "Spanish"
  level = "Professional"

[params.interests]
  enable = true

  [[params.interests.list]]
  name = "Climbing"

  [[params.interests.list]]
  name = "Snowboarding"

  [[params.interests.list]]
  name = "Photography"

  [[params.interests.list]]
  name = "Travelling"

[params.summary]
  enable = true
  text = "Summarise your career here. Donec quam felis, ultricies nec, pellentesque eu. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.  Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh."

[params.experience]
  enable = true

  [[params.experience.list]]
  title = "Senior Software Engineer"
  dates = "2019 - Present"
  company = "Google"
  details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."

  [[params.experience.list.items]]
  details = "Lorem ipsum dolor sit amet, consectetuer."

  [[params.experience.list.items]]
  details = "Aenean commodo ligula eget dolor."

  [[params.experience.list.items]]
  details = "Etiam ultricies nisi vel augue."

  [[params.experience.list]]
  title = "Lead Software Developer"
  dates = "2016 - 2019"
  company = "Apple"
  details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."

  [[params.experience.list.items]]
  details = "Lorem ipsum dolor sit amet, consectetuer."
  
  [[params.experience.list.items]]
  details = "Aenean commodo ligula eget dolor."

  [[params.experience.list]]
  title = "Senior Software Developer"
  dates = "2014 - 2016"
  company = "Dropbox"
  details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

  [[params.experience.list]]
  title = "Senior Developer"
  dates = "2013 - 2014"
  company = "Uber"
  details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

  [[params.experience.list]]
  title = "Backend Developer"
  dates = "2014 - 2016"
  company = "Amazon"
  details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

  [[params.experience.list]]
  title = "Frontend Developer"
  dates = "2013 - 2014"
  company = "Startup"
  details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

[params.projects]
  enable = true

  [[params.projects.list]]
  title = "Project Lorem Ipsum"
  meta = "Open Source"
  tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

  [[params.projects.list]]
  title = "Project Sed Fringilla"
  meta = "Open Source"
  tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

  [[params.projects.list]]
  title = "Project Praesent"
  meta = "Open Source"
  tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

[params.information]
  enable = true

  [[params.information.list]]
  title = "Papers"

  [[params.information.list.items]]
  details = "2018 · Lorem Ipsum"
  
  [[params.information.list.items]]
  details = "2016 · Sed Fringilla"

  [[params.information.list]]
  title = "Interests"
  details = "Climbing, Snowboarding, Photography, Travelling"

# [params.social]
#   enable = true

#   [[params.social.list]]
#   icon = "fab fa-github-square"
#   url = "//github.com/username"
#   title = "username"

#   [[params.social.list]]
#   icon = "fab fa-linkedin"
#   url = "//linkedin.com/in/username"
#   title = "username"

#   [[params.social.list]]
#   icon = "fab fa-twitter-square"
#   url = "//twitter.com/username"
#   title = "@username"
